fix incorrect error messages for from_http()
cloudevents/sdk-python pull request #143
Opened 2021-08-24 12:29 UTC by xinydev

Fixes https://github.com/cloudevents/sdk-python/issues/139

Align the logic of `has_binary_headers()` with [sdk-go](https://github.com/cloudevents/sdk-go/blob/70febdc855835091a1d5f111d9223f226eb0ab0a/v2/protocol/http/message.go#L58-L99)

Using `ce-specversion` is enough.

```go
func NewMessage(header nethttp.Header, body io.ReadCloser) *Message {
	m := Message{Header: header}
	if body != nil {
		m.BodyReader = body
	}
	if m.format = format.Lookup(header.Get(ContentType)); m.format == nil {
		m.version = specs.Version(m.Header.Get(specs.PrefixedSpecVersionName()))
	}
	return &m
}

func (m *Message) ReadEncoding() binding.Encoding {
	if m.version != nil {
		return binding.EncodingBinary
	}
	if m.format != nil {
		return binding.EncodingStructured
	}
	return binding.EncodingUnknown
}
```

## Changes

## One line description for the changelog

- [x] Tests pass
- [x] Appropriate changes to README are included in PR

2021-08-24 12:39 UTC, xinydev commented
PTAL @di

2021-09-02 22:54 UTC, GrahamCampbell commented
This PR is missing tests covering the actual issue.

2021-09-02 23:04 UTC, grant requested changes
Thanks for the PR.

The spec states that binary CEs have required attributes in the headers.

There are 4 required attributes:

https://github.com/cloudevents/spec/blob/v1.0/spec.md#required-attributes

I'm not seeing how this fixes an issue with the function.

2021-09-02 23:05 UTC, grant commented
> Align the logic of `has_binary_headers()` with [sdk-go](https://github.com/cloudevents/sdk-go/blob/70febdc855835091a1d5f111d9223f226eb0ab0a/v2/protocol/http/message.go#L58-L99)

The goal of the SDKs aren't to align to each other, but rather the CE spec. I'm a bit confused why this is mentioned here.

2021-09-02 23:16 UTC, GrahamCampbell commented
I think the complaint here is that the error message when it fails to parse is not very helpful? By removing the extra conditions on trying to process the message as a binary encoding, we are able to provide a more helpful error about missing required attributes, rather than instead trying to process it as structured.

2021-09-02 23:17 UTC, GrahamCampbell commented
Had there been a test included with this, this would have been clearer. :trollface: :P

2021-09-02 23:21 UTC, grant commented
Making the error message better sounds good. However, I don't see this PR fixing #139, so I'm inclined we modify the PR or close it. :)

2021-09-06 15:41 UTC, xinydev commented
PTAL, I added a test case


>  I don't see this PR fixing

Before modification, all http requests with missing necessary headers will be judged as structured content mode(but in fact is binary mode),and than raise an error in L65-L67(`Failed to find specversion in HTTP request`) 

After modification, the http requests with missing necessary headers will throw an error through L76-L78






https://github.com/cloudevents/sdk-python/blob/705e8b41004dba4f9a2dda0993205f9d610c7161/cloudevents/http/http_methods.py#L46-L78

2021-09-17 01:57 UTC, grant requested changes
All of the 4 required CE fields should be check and required.

2021-09-17 01:57 UTC, grant commented on cloudevents/sdk/converters/util.py
> +        or "ce-source" in headers
All of these headers are required.

2021-09-17 01:59 UTC, grant commented
Perhaps come to CloudEvent WG to talk about the PR?

https://github.com/cloudevents/spec#meeting-time

2021-12-10 00:11 UTC, grant commented
Hi @xinydev, lmk if you're still working on this. I left some comments from before.

2021-12-10 02:27 UTC, closed without merging